//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mifinca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleado
    {
        public int id_empleado { get; set; }
        public int id_finca { get; set; }
        public int id_tarea { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string puesto { get; set; }
        public string direccion { get; set; }
        public int telefono { get; set; }
    
        public virtual planilla planilla { get; set; }
        public virtual tarea tarea { get; set; }
    }
}
