//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mifinca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class planilla
    {
        public int id_planilla { get; set; }
        public int id_empleado { get; set; }
        public int id_finca { get; set; }
        public System.DateTime fecha_resolucion { get; set; }
        public string csv_planilla { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual finca finca { get; set; }
    }
}
