//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mifinca.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tarea
    {
        public int id_tarea { get; set; }
        public int id_empleado { get; set; }
        public int id_tipo { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
        public string descripcion { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual tipo_tarea tipo_tarea { get; set; }
    }
}
